import contextlib
import functools
import multiprocessing as mp
import os
from typing import Any

import numpy as np
import tqdm

from random_matrix.input_statistics import input_statistics_logger
from random_matrix.modes.mode_grid import ModeGrid
from random_matrix.utils import array_utils, geometry_utils


class IndexFinder:
    """Class for determining which elements and combinations of elements of
    the scattering matrix have non-zero statistics that need to be calculated
    later on.

    Attributes
    ----------
    mode_grid :
        The ModeGrid object containing all modes used in the simulation.
    logger :
        Logging object used to print information to the console and time
        different operations.
    """

    def __init__(
        self,
        mode_grid: ModeGrid,
        logger: input_statistics_logger.InputStatisticsLogger,
    ) -> None:
        self.mode_grid = mode_grid
        self.logger = logger

    def get_indices(
        self,
    ) -> tuple[
        dict[str, dict[str, set[tuple[int, int]]]],
        dict[str, dict[str, dict[str, list[tuple[int, int]]]]],
    ]:
        """Main method for getting independent elements and indices of
        non-zero statistics"""

        # First determine the independent elements due to reciprocity.
        with self.logger.log("independent_elements"):
            independent_elements = self.get_independent_element_indices()

        self.independent_elements = independent_elements

        # Get indices for where the mean, covariance and pseudo_covariance are
        # non-zero.
        indices = {}
        with self.logger.log("mean"):
            indices["mean"] = self._get_mean_indices(independent_elements)

        with self.logger.log("covariance"):
            indices["covariance"] = self._get_covariance_indices(
                independent_elements
            )

        with self.logger.log("pseudo_covariance"):
            indices["pseudo_covariance"] = self._get_pseudo_covariance_indices(
                independent_elements
            )
        self.indices = indices

        return independent_elements, indices

    def show_report(self) -> None:
        """Prints a report to the console generated by the logger"""

        self.logger.show_report(self.independent_elements, self.indices)

    # -------------------------------------------------------------------------
    # Methods for finding the independent elements (based on reciprocity)
    # -------------------------------------------------------------------------

    def get_independent_element_indices(
        self,
    ) -> dict[str, dict[str, set[tuple[int, int]]]]:
        """Return a nested dictionary ultimately containing lists of
        independent elements of the scattering matrix."""

        elements: dict[str, dict[str, set[tuple[int, int]]]] = {
            "pp": self._get_independent_element_indices_pp(),
            "pe": {},
            "ep": {},
            "ee": {},
        }
        return elements

    def _get_independent_element_indices_pp(
        self,
    ) -> dict[str, set[tuple[int, int]]]:
        """Get the independent elements of the propagating-propagating block
        of the scattering matrix."""

        independent_elements: dict[str, set[tuple[int, int]]] = {
            "t": set(),
            "r": set(),
            "t2": set(),
            "r2": set(),
        }

        indices = self.mode_grid.propagating_indices

        for i in self.logger.progress_bar(indices):
            for j in indices:
                # All elements of t must be included
                independent_elements["t"].add((i, j))

                if not self.mode_grid.is_reciprocal:
                    independent_elements["t2"].add((i, j))
                    independent_elements["r"].add((i, j))
                    independent_elements["r2"].add((i, j))
                else:
                    # Only accept elements above or on the anti-diagonals of
                    # r and r2.
                    # No elements of t2 are accepted, since it can be found
                    # entirely from t by reciprocity.
                    if i + j <= 0:
                        independent_elements["r"].add((i, j))
                        independent_elements["r2"].add((i, j))

        return independent_elements

    # -------------------------------------------------------------------------
    # Methods for finding the indices where the mean is non-zero
    # -------------------------------------------------------------------------

    def _get_mean_indices(
        self, independent_elements: dict[str, dict[str, set[tuple[int, int]]]]
    ) -> dict[str, dict[str, list[tuple[int, int]]]]:
        """Get indices of the scattering matrix for which the mean needs to
        be calculated."""

        mean_indices: dict[str, dict[str, list[tuple[int, int]]]] = {
            "pp": self._get_mean_indices_pp(independent_elements["pp"]),
            "pe": {},
            "ep": {},
            "ee": {},
        }
        return mean_indices

    def _get_mean_indices_pp(
        self, independent_elements: dict[str, set[tuple[int, int]]]
    ) -> dict[str, list[tuple[int, int]]]:
        """Get indices of 2x2 blocks in the pp section of the scattering
        matrix for which the mean needs to be calculated.

        Currently uses a delta function implementation.
        """

        mean_indices: dict[str, list[tuple[int, int]]] = {
            "t": [],
            "r": [],
            "t2": [],
            "r2": [],
        }

        indices = self.mode_grid.propagating_indices

        for index in self.logger.progress_bar(indices):
            new_indices = (index, index)
            if new_indices in independent_elements["t"]:
                mean_indices["t"].append(new_indices)
            if new_indices in independent_elements["r"]:
                mean_indices["r"].append(new_indices)
            if new_indices in independent_elements["t2"]:
                mean_indices["t2"].append(new_indices)
            if new_indices in independent_elements["r2"]:
                mean_indices["r2"].append(new_indices)

        return mean_indices

    # -------------------------------------------------------------------------
    # Methods for finding the indices where the covariance is non-zero
    # -------------------------------------------------------------------------

    def _get_covariance_indices(
        self, independent_elements: dict[str, dict[str, set[tuple[int, int]]]]
    ) -> dict[str, dict[str, list[tuple[int, int, int, int]]]]:
        """Get quadruples of indices of the scattering matrix for which the
        covariance needs to be calculated.

        Quadruples should be understood in the order (i,j,u,v)
        """

        covariance_indices: dict[
            str, dict[str, set[tuple[int, int, int, int]]]
        ] = {
            "pp,pp": self._get_covariance_indices_pppp(
                independent_elements["pp"], independent_elements["pp"]
            ),
            "pp,pe": {},
            "pp,ep": {},
            "pp,ee": {},
            "pe,pe": {},
            "pe,ep": {},
            "pe,ee": {},
            "ep,ep": {},
            "ep,ee": {},
            "ee,ee": {},
        }
        return covariance_indices  # type: ignore

    def _get_covariance_indices_pppp(
        self,
        independent_elements_one: dict[str, set[tuple[int, int]]],
        independent_elements_two: dict[str, set[tuple[int, int]]],
    ) -> dict[str, list[tuple[int, int, int, int]]]:
        """Get indices of 2x2 blocks in the pp section of the scattering
        matrix for which the mean needs to be calculated.

        Currently uses a delta function implementation.
        """

        covariance_indices: dict[str, list[tuple[int, int, int, int]]] = {
            "t,t": [],
            "t,r": [],
            "t,t2": [],
            "t,r2": [],
            "r,r": [],
            "r,t2": [],
            "r,r2": [],
            "t2,t2": [],
            "t2,r2": [],
            "r2,r2": [],
        }

        indices = self.mode_grid.propagating_indices
        num_indices = len(indices)

        elements = [
            (index_i * num_indices + index_j, i, j)
            for index_i, i in enumerate(indices)
            for index_j, j in enumerate(indices)
        ]

        # Multiprocessing parameters
        # None check avoids a bug. If os cannot detect number of cores,
        # just use one
        num_elements = len(elements)
        num_cores = os.cpu_count()
        num_processes = (
            min(num_elements, num_cores) if num_cores is not None else 1
        )

        # Prepare function and arguments for multiprocessing
        parallelised_function = functools.partial(
            self._get_covariance_indices_pppp_partial,
            mode_grid=self.mode_grid,
            independent_elements_one=independent_elements_one,
            independent_elements_two=independent_elements_two,
            elements=elements,
            progress_bar=self.logger.progress_bar,
        )
        partial_elements = array_utils.split_list(elements, num_processes)

        # Run function in parallel
        with mp.Pool(processes=num_processes) as pool:
            output = pool.map(parallelised_function, partial_elements)

        # Combine results from different processes
        for new_covariance_indices in output:
            for key in covariance_indices:
                covariance_indices[key] += new_covariance_indices[key]

        return covariance_indices

    @staticmethod
    def _get_covariance_indices_pppp_partial(
        partial_elements: list[tuple[int, int, int]],
        mode_grid: ModeGrid,
        independent_elements_one: dict[str, set[tuple[int, int]]],
        independent_elements_two: dict[str, set[tuple[int, int]]],
        elements: list[tuple[int, int, int]],
        progress_bar: Any,
    ) -> dict[str, list[tuple[int, int, int, int]]]:
        """Get indices of 2x2 blocks in the pp section of the scattering
        matrix for which the mean needs to be calculated.

        Currently uses a delta function implementation.

        One of many processes that run concurrently.
        """

        covariance_indices: dict[str, list[tuple[int, int, int, int]]] = {
            "t,t": [],
            "t,r": [],
            "t,t2": [],
            "t,r2": [],
            "r,r": [],
            "r,t2": [],
            "r,r2": [],
            "t2,t2": [],
            "t2,r2": [],
            "r2,r2": [],
        }

        weight_dict = mode_grid.weight_dict
        vertices_dict = mode_grid.vertices_dict
        centers_dict = mode_grid.centers_dict

        # Area used to determine whether memory effect type correlations are
        # kept or not
        central_mode_vertices = vertices_dict[0]
        central_area = geometry_utils.get_minkowski_filter_area(
            central_mode_vertices,
            central_mode_vertices,
            central_mode_vertices,
            central_mode_vertices,
        )
        tol = 1e-8
        threshold_area = central_area / 10.0 - tol
        central_weight_tol = weight_dict[0] - tol
        memory_effect_vector_norm_threshold = central_area - tol
        memory_effect_vector_norm_threshold = tol

        for index_one, i, j in progress_bar(partial_elements):
            # Second loop starts form index one. We can ignore half of
            # the cases, because they're just the same thing with the order
            # of the shapes swapped.
            for _, u, v in elements[index_one:]:

                # We do checks to test if the correlation should be calculated
                # or not. If we pass, we keep it. If we continue we skip it.

                # Always calculate autocorrelations
                is_autocorrelation = i == u and j == v
                if is_autocorrelation:
                    update_covariance_indices(
                        i,
                        j,
                        u,
                        v,
                        covariance_indices,
                        independent_elements_one,
                        independent_elements_two,
                    )
                    continue
                
                # Skip correlations for small edge modes
                min_weight = min(
                    weight_dict[i],
                    weight_dict[j],
                    weight_dict[u],
                    weight_dict[v],
                )
                is_small_weight = min_weight < central_weight_tol
                if is_small_weight:
                    continue

                # Check the memory effect condition quickly to kill off
                # obvious bad candidates and keep obviously good candidates
                memory_effect_vector = (
                    centers_dict[i]
                    - centers_dict[j]
                    - centers_dict[u]
                    + centers_dict[v]
                )
                squared_norm = (
                    memory_effect_vector[0] ** 2 + memory_effect_vector[1] ** 2
                )
                is_zero_memory_effect_vector_norm = squared_norm < tol
                if is_zero_memory_effect_vector_norm:
                    update_covariance_indices(
                        i,
                        j,
                        u,
                        v,
                        covariance_indices,
                        independent_elements_one,
                        independent_elements_two,
                    )
                    continue

                is_large_memory_effect_vector_norm = (
                    squared_norm > memory_effect_vector_norm_threshold
                )
                if is_large_memory_effect_vector_norm:
                    continue

                # # For the final survivors
                # intersection_area = geometry_utils.get_minkowski_filter_area(
                #     vertices_dict[i],
                #     vertices_dict[j],
                #     vertices_dict[u],
                #     vertices_dict[v],
                # )
                # # If the area is too small (compared to our threshold),
                # # we ignore these correlations
                # if intersection_area < threshold_area:
                #     print("Mode failed minkowski filter")
                #     print(i, j, u, v)
                #     continue

                # Final survivors are kept
                update_covariance_indices(
                    i,
                    j,
                    u,
                    v,
                    covariance_indices,
                    independent_elements_one,
                    independent_elements_two,
                )

        return covariance_indices

    # -------------------------------------------------------------------------
    # Methods for finding the indices where the pseudo-covariance is non-zero
    # -------------------------------------------------------------------------

    def _get_pseudo_covariance_indices(
        self, independent_elements: dict[str, dict[str, list[tuple[int, int]]]]
    ) -> dict[str, dict[str, set[tuple[int, int, int, int]]]]:
        """Get indices of the scattering matrix for which the pseudo-covariance
        needs tobe calculated."""

        pseudo_covariance_indices = {
            "pp,pp": self._get_pseudo_covariance_indices_pppp(
                independent_elements["pp"]
            ),
            "pp,pe": {},
            "pp,ep": {},
            "pp,ee": {},
            "pe,pe": {},
            "pe,ep": {},
            "pe,ee": {},
            "ep,ep": {},
            "ep,ee": {},
            "ee,ee": {},
        }
        return pseudo_covariance_indices

    def _get_pseudo_covariance_indices_pppp(
        self, independent_elements: dict[str, dict[str, list[tuple[int, int]]]]
    ) -> dict[str, set[tuple[int, int, int, int]]]:
        return {}

    # -------------------------------------------------------------------------
    # Computed properties
    # -------------------------------------------------------------------------

    @property
    def num_independent_elements(self):
        independent_elements = self.independent_element_indices
        independent_elements = independent_elements["pp"]
        total = (
            len(independent_elements["t"])
            + len(independent_elements["r"])
            + len(independent_elements["t2"])
            + len(independent_elements["r2"])
        )
        return total


def update_covariance_indices(
    i: int,
    j: int,
    u: int,
    v: int,
    covariance_indices: dict,
    independent_elements_one: dict,
    independent_elements_two: dict,
) -> None:
    """Update covariance_indices dictionary with the correlation (i,j,u,v)."""

    covariance_indices["t,t"].append((i, j, u, v))
    # if (u, v) in independent_elements_two["r"]:
    #     covariance_indices["t,r"].append((i, j, u, v))
    # if (u, v) in independent_elements_two["t2"]:
    #     covariance_indices["t,t2"].append((i, j, u, v))
    # if (u, v) in independent_elements_two["r2"]:
    #     covariance_indices["t,r2"].append((i, j, u, v))

    # Correlations of r with others
    if (i, j) in independent_elements_one["r"]:
        if (u, v) in independent_elements_two["r"]:
            covariance_indices["r,r"].append((i, j, u, v))
        # if (u, v) in independent_elements_two["t2"]:
        #     covariance_indices["r,t2"].append((i, j, u, v))
        # if (u, v) in independent_elements_two["r2"]:
        #     covariance_indices["r,r2"].append((i, j, u, v))

    # Correlations of t2 with others
    if (i, j) in independent_elements_one["t2"]:
        if (u, v) in independent_elements_two["t2"]:
            covariance_indices["t2,t2"].append((i, j, u, v))
        # if (u, v) in independent_elements_two["r2"]:
        #     covariance_indices["t2,r2"].append((i, j, u, v))

    # Correlations of r2 with others
    if (i, j) in independent_elements_one["r2"]:
        if (u, v) in independent_elements_two["r2"]:
            covariance_indices["r2,r2"].append((i, j, u, v))
