import functools
import multiprocessing as mp
import os

import numpy as np
import tqdm

from random_matrix.input_statistics.input_statistics_logger import (
    IndexFinderLogger,
)
from random_matrix.modes.mode_grid import ModeGrid
from random_matrix.utils import array_utils, geometry_utils


class IndexFinder:
    """Class for determining which elements and combinations of elements of
    the scattering matrix have non-zero statistics that need to be calculated
    later on.

    Attributes
    ----------
    mode_grid :
        The ModeGrid object containing all modes used in the simulation.
    logger :
        Logging object used to print information to the console and time
        different operations.
    """

    def __init__(
        self,
        mode_grid: ModeGrid,
        logger: IndexFinderLogger = IndexFinderLogger(),
    ) -> None:
        self.mode_grid = mode_grid
        self.logger = logger

    def get_indices(
        self,
    ) -> tuple[
        dict[str, dict[str, set[tuple[int, int]]]],
        dict[str, dict[str, dict[str, list[tuple[int, int]]]]],
    ]:
        """Main method for getting independent elements and indices of
        non-zero statistics."""

        # First determine the independent elements due to reciprocity.
        with self.logger.log("independent_elements"):
            independent_elements = self.get_independent_element_indices()
        self.independent_elements = independent_elements

        # Get indices for where the mean, covariance and pseudo_covariance are
        # non-zero.
        indices = {}
        with self.logger.log("mean"):
            indices["mean"] = self._get_mean_indices(independent_elements)
        with self.logger.log("covariance"):
            indices["covariance"] = self._get_covariance_indices(
                independent_elements
            )
        with self.logger.log("pseudo_covariance"):
            indices["pseudo_covariance"] = self._get_pseudo_covariance_indices(
                independent_elements
            )
        self.indices = indices

        return independent_elements, indices

    def show_report(self) -> None:
        """Prints a report to the console generated by the logger"""

        self.logger.show_report(self.independent_elements, self.indices)

    # -------------------------------------------------------------------------
    # Methods for finding the independent elements (based on reciprocity)
    # -------------------------------------------------------------------------

    def get_independent_element_indices(
        self,
    ) -> dict[str, dict[str, set[tuple[int, int]]]]:
        """Return a nested dictionary ultimately containing lists of
        independent elements of the scattering matrix."""

        elements: dict[str, dict[str, set[tuple[int, int]]]] = {
            "pp": self._get_independent_element_indices_pp(),
            "pe": {},
            "ep": {},
            "ee": {},
        }
        return elements

    def _get_independent_element_indices_pp(
        self,
    ) -> dict[str, set[tuple[int, int]]]:
        """Get the independent elements of the propagating-propagating block
        of the scattering matrix."""

        independent_elements: dict[str, set[tuple[int, int]]] = {
            "t": set(),
            "r": set(),
            "t2": set(),
            "r2": set(),
        }

        indices = self.mode_grid.propagating_indices

        for i in tqdm.tqdm(indices):
            for j in indices:
                # All elements of t must be included
                independent_elements["t"].add((j, i))

                if not self.mode_grid.is_reciprocal:
                    independent_elements["t2"].add((j, i))
                    independent_elements["r"].add((j, i))
                    independent_elements["r2"].add((j, i))
                else:
                    # Only accept elements above or on the anti-diagonals of
                    # r and r2.
                    # No elements of t2 are accepted, since it can be found
                    # entirely from t by reciprocity.
                    if i + j <= 0:
                        independent_elements["r"].add((j, i))
                        independent_elements["r2"].add((j, i))

        return independent_elements

    # -------------------------------------------------------------------------
    # Methods for finding the indices where the mean is non-zero
    # -------------------------------------------------------------------------

    def _get_mean_indices(
        self, independent_elements: dict[str, dict[str, set[tuple[int, int]]]]
    ) -> dict[str, dict[str, list[tuple[int, int]]]]:
        """Get indices of the scattering matrix for which the mean needs to
        be calculated."""

        mean_indices: dict[str, dict[str, list[tuple[int, int]]]] = {
            "pp": self._get_mean_indices_pp(independent_elements["pp"]),
            "pe": {},
            "ep": {},
            "ee": {},
        }
        return mean_indices

    def _get_mean_indices_pp(
        self, independent_elements: dict[str, set[tuple[int, int]]]
    ) -> dict[str, list[tuple[int, int]]]:
        """Get indices of 2x2 blocks in the pp section of the scattering
        matrix for which the mean needs to be calculated.

        Currently uses a delta function implementation.
        """

        mean_indices: dict[str, list[tuple[int, int]]] = {
            "t": [],
            "r": [],
            "t2": [],
            "r2": [],
        }

        indices = self.mode_grid.propagating_indices

        for index in tqdm.tqdm(indices):
            new_indices = (index, index)
            if new_indices in independent_elements["t"]:
                mean_indices["t"].append(new_indices)
            if new_indices in independent_elements["r"]:
                mean_indices["r"].append(new_indices)
            if new_indices in independent_elements["t2"]:
                mean_indices["t2"].append(new_indices)
            if new_indices in independent_elements["r2"]:
                mean_indices["r2"].append(new_indices)

        return mean_indices

    # -------------------------------------------------------------------------
    # Methods for finding the indices where the covariance is non-zero
    # -------------------------------------------------------------------------

    def _get_covariance_indices(
        self, independent_elements: dict[str, dict[str, set[tuple[int, int]]]]
    ) -> dict[str, dict[str, list[tuple[int, int, int, int]]]]:
        """Get quadruples of indices of the scattering matrix for which the
        covariance needs to be calculated.

        Quadruples should be understood in the order (i,j,u,v)
        """

        covariance_indices: dict[
            str, dict[str, set[tuple[int, int, int, int]]]
        ] = {
            "pp,pp": self._get_covariance_indices_pppp(
                independent_elements["pp"], independent_elements["pp"]
            ),
            "pp,pe": {},
            "pp,ep": {},
            "pp,ee": {},
            "pe,pe": {},
            "pe,ep": {},
            "pe,ee": {},
            "ep,ep": {},
            "ep,ee": {},
            "ee,ee": {},
        }
        return covariance_indices  # type: ignore

    def _get_covariance_indices_pppp(
        self,
        independent_elements_one: dict[str, set[tuple[int, int]]],
        independent_elements_two: dict[str, set[tuple[int, int]]],
    ) -> dict[str, list[tuple[int, int, int, int]]]:
        """Get indices of 2x2 blocks in the pp section of the scattering
        matrix for which the mean needs to be calculated.

        Currently uses a delta function implementation.
        """

        covariance_indices: dict[str, list[tuple[int, int, int, int]]] = {
            "t,t": [],
            "t,r": [],
            "t,t2": [],
            "t,r2": [],
            "r,r": [],
            "r,t2": [],
            "r,r2": [],
            "t2,t2": [],
            "t2,r2": [],
            "r2,r2": [],
        }

        indices = self.mode_grid.propagating_indices
        num_indices = len(indices)

        elements = [
            (index_i * num_indices + index_j, i, j)
            for index_i, i in enumerate(indices)
            for index_j, j in enumerate(indices)
        ]

        # Multiprocessing parameters
        # None check avoids a bug. If os cannot detect number of cores,
        # just use one
        num_elements = len(elements)
        num_cores = os.cpu_count()
        num_processes = (
            min(num_elements, num_cores) if num_cores is not None else 1
        )

        # Prepare function and arguments for multiprocessing
        parallelised_function = functools.partial(
            self._get_covariance_indices_pppp_partial,
            mode_grid=self.mode_grid,
            independent_elements_one=independent_elements_one,
            independent_elements_two=independent_elements_two,
            elements=elements,
        )
        partial_elements = array_utils.split_list(elements, num_processes)

        # Run function in parallel
        with mp.Pool(processes=num_processes) as pool:
            output = pool.map(parallelised_function, partial_elements)

        # Combine results from different processes
        for new_covariance_indices in output:
            for key in covariance_indices:
                covariance_indices[key] += new_covariance_indices[key]

        return covariance_indices

    @staticmethod
    def _get_covariance_indices_pppp_partial(
        mode_grid: ModeGrid,
        independent_elements_one: dict[str, set[tuple[int, int]]],
        independent_elements_two: dict[str, set[tuple[int, int]]],
        elements: list[tuple[int, int, int]],
        partial_elements: list[tuple[int, int, int]],
    ) -> dict[str, list[tuple[int, int, int, int]]]:
        """Get indices of 2x2 blocks in the pp section of the scattering
        matrix for which the mean needs to be calculated.

        Currently uses a delta function implementation.

        One of many processes that run concurrently.
        """

        covariance_indices: dict[str, list[tuple[int, int, int, int]]] = {
            "t,t": [],
            "t,r": [],
            "t,t2": [],
            "t,r2": [],
            "r,r": [],
            "r,t2": [],
            "r,r2": [],
            "t2,t2": [],
            "t2,r2": [],
            "r2,r2": [],
        }

        # Area used to determine whether memory effect type correlations are
        # kept or not
        threshold_area = mode_grid.by_index(mode_grid.central_index).weight * 2

        for index_one, i, j in tqdm.tqdm(partial_elements):
            # Second loop starts form index one. We can ignore half of
            # the cases, because they're just the same thing with the order
            # of the shapes swapped.
            for _, u, v in elements[index_one:]:
                # Check here for autocorrelations
                # Autocorrelations MUST be included, because they are
                # essentially mean intensities. For autocorrelations we don't
                # need to do any other checks.
                is_autocorrelation = i == u and j == v

                if not is_autocorrelation:
                    # Here we are looking at off-diagonal terms of the
                    # correlation matrix. These will be memory effect type
                    # correlations.

                    # Get all four modes
                    mode_i = mode_grid.by_index(i).vertices
                    mode_j = mode_grid.by_index(j).vertices
                    mode_u = mode_grid.by_index(u).vertices
                    mode_v = mode_grid.by_index(v).vertices

                    # Find the centroids
                    mean_i = np.mean(mode_i, axis=0)
                    mean_j = np.mean(mode_j, axis=0)
                    centre_ij = np.mean(np.vstack((mean_i, mean_j)), axis=0)
                    mean_u = np.mean(mode_u, axis=0)
                    mean_v = np.mean(mode_v, axis=0)
                    centre_uv = np.mean(np.vstack((mean_u, mean_v)), axis=0)

                    # Find the difference space associated with centre_ij
                    mode_j_ref = geometry_utils.reflect_through_point(
                        mode_j, centre_ij
                    )
                    ij_intersect = geometry_utils.intersection(
                        mode_i, mode_j_ref
                    )
                    new_ij = 2 * geometry_utils.translate_points(
                        ij_intersect, -centre_ij
                    )

                    # Find the difference space associated with centre_uv
                    mode_v_ref = geometry_utils.reflect_through_point(
                        mode_v, centre_uv
                    )
                    uv_intersect = geometry_utils.intersection(
                        mode_u, mode_v_ref
                    )
                    new_uv = 2 * geometry_utils.translate_points(
                        uv_intersect, -centre_uv
                    )

                    # Find the intersection of the difference spaces and get
                    # its area
                    ijuv_intersect = geometry_utils.intersection(
                        new_ij, new_uv
                    )
                    area = geometry_utils.get_polygon_area(ijuv_intersect)

                    # If the area is too small (compared to our threshold),
                    # we ignore these correlations
                    if (
                        np.isclose(area, threshold_area)
                        or area < threshold_area
                    ):
                        continue

                # If we reach this point, we have found a correlation that must
                # be calculated. Which blocks it must be found for, however,
                # depends on the independent elements
                covariance_indices["t,t"].append((i, j, u, v))
                if (u, v) in independent_elements_two["r"]:
                    covariance_indices["t,r"].append((i, j, u, v))
                if (u, v) in independent_elements_two["t2"]:
                    covariance_indices["t,t2"].append((i, j, u, v))
                if (u, v) in independent_elements_two["r2"]:
                    covariance_indices["t,r2"].append((i, j, u, v))

                # Correlations of r with others
                if (i, j) in independent_elements_one["r"]:
                    if (u, v) in independent_elements_two["r"]:
                        covariance_indices["r,r"].append((i, j, u, v))
                    if (u, v) in independent_elements_two["t2"]:
                        covariance_indices["r,t2"].append((i, j, u, v))
                    if (u, v) in independent_elements_two["r2"]:
                        covariance_indices["r,r2"].append((i, j, u, v))

                # Correlations of t2 with others
                if (i, j) in independent_elements_one["t2"]:
                    if (u, v) in independent_elements_two["t2"]:
                        covariance_indices["t2,t2"].append((i, j, u, v))
                    if (u, v) in independent_elements_two["r2"]:
                        covariance_indices["t2,r2"].append((i, j, u, v))

                # Correlations of r2 with others
                if (i, j) in independent_elements_one["r2"]:
                    if (u, v) in independent_elements_two["r2"]:
                        covariance_indices["r2,r2"].append((i, j, u, v))

        return covariance_indices

    # -------------------------------------------------------------------------
    # Methods for finding the indices where the pseudo-covariance is non-zero
    # -------------------------------------------------------------------------

    def _get_pseudo_covariance_indices(
        self, independent_elements: dict[str, dict[str, list[tuple[int, int]]]]
    ) -> dict[str, dict[str, set[tuple[int, int, int, int]]]]:
        """Get indices of the scattering matrix for which the pseudo-covariance
        needs tobe calculated."""

        pseudo_covariance_indices = {
            "pp,pp": self._get_pseudo_covariance_indices_pppp(
                independent_elements["pp"]
            ),
            "pp,pe": {},
            "pp,ep": {},
            "pp,ee": {},
            "pe,pe": {},
            "pe,ep": {},
            "pe,ee": {},
            "ep,ep": {},
            "ep,ee": {},
            "ee,ee": {},
        }
        return pseudo_covariance_indices

    def _get_pseudo_covariance_indices_pppp(
        self, independent_elements: dict[str, dict[str, list[tuple[int, int]]]]
    ) -> dict[str, set[tuple[int, int, int, int]]]:
        return {}

    # -------------------------------------------------------------------------
    # Computed properties
    # -------------------------------------------------------------------------

    @property
    def num_independent_elements(self):
        independent_elements = self.independent_element_indices
        independent_elements = independent_elements["pp"]
        total = (
            len(independent_elements["t"])
            + len(independent_elements["r"])
            + len(independent_elements["t2"])
            + len(independent_elements["r2"])
        )
        return total
